name: 'Packer Deployment'

on:
  pull_request:
    paths:
      - 'avd/packer/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  Windows-11:
    uses: Coretek-Simpsonm/Ansible_EUC_Simpson/.github/workflows/packer-check-job.yml@main
    with:
      build-template: avd-win11.pkr.hcl
      version: ${{ github.event.inputs.version }}
    secrets: inherit
